[[lines]]
  pat  = "^(.*?) .*? .*? \\[(.*?)\\] \".*?\" .*? .*? \".*?\" \"(.*?)\""
  colors = ["White", "LightGreen", "LightBlue", "Green"]
  [[lines.tokens]]
    pat   = "GET"
    colors = ["LightCyan"]
  [[lines.tokens]]
    pat   = "POST"
    colors = ["LightYellow"]
  [[lines.tokens]]
    pat   = "HEAD"
    colors = ["LightMagenta"]

[[lines]]
  pat  = "^(.{3} [0-9]{2} [0-9:]{8}) (.*?) (postfix/.*?\\[.*?\\]|dovecot):.*"
  colors = ["White", "LightGreen", "Green", "LightBlue"]
  [[lines.tokens]]
    pat   = "error"
    colors = ["LightRed"]

